### ISSUE TITLE
Change Resource handling

### ISSUE THREAD

**Issue by MRossol** [NREL/rex#105]
**Why this feature is necessary:**
Make resource dataset slicing more intuitive i.e. ['dataset'][slice]

**A possible solution is:**
Have Resource.__getitem__ return ResourceDataset which has its own getitem

**Charge code**
HSDS?

**Urgency / Timeframe**
Not Urgent

**Comment by MRossol** [comment]
@grantbuster  What do you think of this idea? It would be a big change that would require updates to lots of downstream code, but would make it a lot "clearer"

**Comment by grantbuster** [comment]
Lol it seems unnecessary at first glance. Whats the motivation for this? I guess it would bring the Resource handler more in-line with h5py but still, seems like a pretty trivial difference to warrant changing our hundreds of thousands of lines of code.

**Comment by MRossol** [comment]
Bannister brought it up. I agree that at first I balked but I realized that since we started the code we've implemented some architectural changes that would allow this and would move it in line with h5py. I agree that its likely not worth it but thought I'd put it out there...

**Comment by grantbuster** [comment]
I think in a perfect world it might be worth doing but I think it is wildly low priority haha like only if we have literally nothing else to do and a bunch of extra funds.

**Comment by MRossol** [comment]
So I realized that this won't be nearly as simple as I thought for WindResource or MultiTime/MultiYear Resource so I'm closing it. What we have is 1000% fine
