### ISSUE TITLE
Need an error message when missing a required sam variable

### ISSUE THREAD

**Issue by grantbuster** [NREL/rex#127]
**Bug Description**
See https://github.com/NREL/reV/issues/369

**Expected behavior**
Error message that says "missing pressure from file: {}"

**Comment by grantbuster** [comment]
Yeah that seems like a good place, probably also in the preload_SAM methods (there might be a few more):

https://github.com/NREL/rex/blob/17392404b816c4c8f29cadc54adb3cf072fcbca7/rex/renewable_resource.py#L243-L246
https://github.com/NREL/rex/blob/17392404b816c4c8f29cadc54adb3cf072fcbca7/rex/renewable_resource.py#L1057-L1060

**Comment by ppinchuk** [comment]
So the `preload_SAM` methods should be covered with a message already: 
https://github.com/NREL/rex/blob/17392404b816c4c8f29cadc54adb3cf072fcbca7/rex/resource.py#L1247-L1249

That should get raised when it tries ` self[var, time_slice, sites]`.

I will add a WindResource test to verify this behavior
