### ISSUE TITLE
WaveX parameter `directional_wave_spectrum` when calling `get_lat_lon_df` 

### ISSUE THREAD

**Issue by ssolson** [NREL/rex#133]
**Bug Description**
The parameter `directional_wave_spectrum` when calling `get_lat_lon_df` on the path: '/nrel/US_wave/virtual_buoy/West_Coast/West_Coast_virtual_buoy_1995.h5' returns an array of size 0. 

However, if I change the parameter to `energy_period` I get the expected result. This call was working previously on MHKiT.

**Full Traceback**
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Input In [50], in <cell line: 2>()
      4 time_index = rex_waves.time_index
      5 # data_raw = rex_waves.get_lat_lon_df('energy_period',(43.489171,-125.152137))
----> 6 data_raw = rex_waves.get_lat_lon_df('directional_wave_spectrum',(43.489171,-125.152137))

Input In [50], in <cell line: 2>()
      4 time_index = rex_waves.time_index
      5 # data_raw = rex_waves.get_lat_lon_df('energy_period',(43.489171,-125.152137))
----> 6 data_raw = rex_waves.get_lat_lon_df('directional_wave_spectrum',(43.489171,-125.152137))

File ~\anaconda3\lib\site-packages\rex\resource_extraction\resource_extraction.py:786, in ResourceX.get_lat_lon_df(self, ds_name, lat_lon, check_lat_lon)
    763 """
    764 Extract timeseries of site(s) nearest to given lat_lon(s) and return
    765 as a DataFrame
   (...)
    783     Time-series DataFrame for given site(s) and dataset
    784 """
    785 gid = self.lat_lon_gid(lat_lon, check_lat_lon=check_lat_lon)
--> 786 df = self.get_gid_df(ds_name, gid)
    788 return df

File ~\anaconda3\lib\site-packages\rex\resource_extraction\resource_extraction.py:1863, in WaveX.get_gid_df(self, ds_name, gid)
   1846 """
   1847 Extract timeseries of site(s) nearest to given lat_lon(s) and return
   1848 as a DataFrame
   (...)
   1860     Time-series DataFrame for given site(s) and dataset
   1861 """
   1862 if ds_name == 'directional_wave_spectrum':
-> 1863     df = self[ds_name, :, :, :, gid]
   1864     index = pd.MultiIndex.from_product(
   1865         [self.time_index, self['frequency'], self['direction']],
   1866         names=['time_index', 'frequency', 'direction'])
   1867     ax1 = np.product(df.shape[:3])

File ~\anaconda3\lib\site-packages\rex\resource_extraction\resource_extraction.py:103, in ResourceX.__getitem__(self, keys)
    102 def __getitem__(self, keys):
--> 103     return self.resource[keys]

File ~\anaconda3\lib\site-packages\rex\resource.py:626, in BaseResource.__getitem__(self, keys)
    624         raise ResourceRuntimeError(msg)
    625 else:
--> 626     out = self._get_ds(ds, ds_slice)
    628 return out

File ~\anaconda3\lib\site-packages\rex\resource.py:1248, in BaseResource._get_ds(self, ds_name, ds_slice)
   1246 ds = self.h5[ds_name]
   1247 ds_slice = parse_slice(ds_slice)
-> 1248 out = ResourceDataset.extract(ds, ds_slice, scale_attr=self.SCALE_ATTR,
   1249                               add_attr=self.ADD_ATTR,
   1250                               unscale=self._unscale)
   1252 return out

File ~\anaconda3\lib\site-packages\rex\resource.py:530, in ResourceDataset.extract(cls, ds, ds_slice, scale_attr, add_attr, unscale)
    510 """
    511 Extract data from Resource Dataset
    512 
   (...)
    525     Flag to unscale dataset data, by default True
    526 """
    527 dset = cls(ds, scale_attr=scale_attr, add_attr=add_attr,
    528            unscale=unscale)
--> 530 return dset[ds_slice]

File ~\anaconda3\lib\site-packages\rex\resource.py:50, in ResourceDataset.__getitem__(self, ds_slice)
     47 def __getitem__(self, ds_slice):
     48     ds_slice = parse_slice(ds_slice)
---> 50     return self._get_ds_slice(ds_slice)

File ~\anaconda3\lib\site-packages\rex\resource.py:500, in ResourceDataset._get_ds_slice(self, ds_slice)
    498         out = self._extract_list_slice(ds_slice)
    499 else:
--> 500     out = self._extract_ds_slice(ds_slice)
    502 if self._unscale:
    503     out = self._unscale_data(out)

File ~\anaconda3\lib\site-packages\rex\resource.py:445, in ResourceDataset._extract_ds_slice(self, ds_slice)
    442     if ax_idx is not None:
    443         idx_slice += (ax_idx,)
--> 445 out = self.ds[slices]
    447 # check to see if idx_slice needs to be applied
    448 if any(s != slice(None) if isinstance(s, slice) else True
    449        for s in idx_slice):

File ~\anaconda3\lib\site-packages\h5pyd\_hl\dataset.py:1146, in Dataset.__getitem__(self, args, new_dtype)
   1144     self.log.info("binary response, {} bytes".format(len(rsp)))
   1145     #arr1d = numpy.frombuffer(rsp, dtype=mtype)
-> 1146     arr1d = bytesToArray(rsp, mtype, page_mshape)
   1147     page_arr = numpy.reshape(arr1d, page_mshape)
   1148 elif "shm_name" in rsp:
   1149     # passed a shared memory object

File ~\anaconda3\lib\site-packages\h5pyd\_hl\base.py:569, in bytesToArray(data, dt, shape)
    567         arr = arr.reshape(dt.shape)
    568     else:
--> 569         arr = arr.reshape(shape)
    570 return arr

ValueError: cannot reshape array of size 0 into shape (8748,29,24)
```

**Code Sample**
```
wave_file='/nrel/US_wave/virtual_buoy/West_Coast/West_Coast_virtual_buoy_2010.h5'
with WaveX(wave_file, hsds=True) as rex_waves:
    meta = rex_waves.meta
    time_index = rex_waves.time_index
    data_raw = rex_waves.get_lat_lon_df('directional_wave_spectrum',(43.489171,-125.152137))
    # data_raw = rex_waves.get_lat_lon_df('energy_period',(43.489171,-125.152137))
```

**To Reproduce**
Use the code sample above

**Expected behavior**
I expect to receive a dataframe as when using the parameter `energy_period`

**System (please complete the following information):**
 - OS: OSX, Windows, Linux
 - Compute hardware (Actions, local machine)
 - Version [0.2.68]
 - 0.2.68 is my local machine but I have tried this on most of the recent versions and all OS using Github actions. I can't seem to fix it

**Additional context**
Used in MHKiT https://github.com/MHKiT-Software/MHKiT-Python/pull/194#issuecomment-1289285474

**Charge code**
Please reach out to Rebecca Fao.

**Comment by grantbuster** [comment]
@ssolson, the `directional_wave_spectrum` dataset is 4-dimensional and therefore does not conform to a standard spatiotemporal NREL resource data format, especially when requesting an extraction to a dataframe. What is your expected behavior here?

**Comment by grantbuster** [comment]
charge code from Rebecca: WAPP.10343.24.01.01 – MHKiT

**Comment by grantbuster** [comment]
One option for you is the following which will extract the data at a given site to a 3D numpy array, but we have no plans to support 3D dataframes in the `get_lat_lon_df()` method. I would highly recommend testing the following code, as this is well beyond the verification basis of our test suite.

![image](https://user-images.githubusercontent.com/12700356/199115539-3c1c0883-89ed-4f78-9925-b0c1bc905d97.png)

**Comment by ssolson** [comment]
Hey Grant. Thank you for taking a look. So to answer your question first the expected behavior is in the posted issue. It should return a DataFrame the same as the energy period. Second to address your comment "we have no plans to support 3D DataFrames". The issue I am raising was not a 3D DataFrame and it had been working for over a year.  In MHKiT we have a  function dedicated to using `get_lat_lon_df` with `directional_wave_spectrum` [here](https://github.com/MHKiT-Software/MHKiT-Python/blob/21ff3a24c37c528b3e2b087a486fc1b80a932a16/mhkit/wave/io/hindcast.py#L155).  We have CI tests that use it that our package that the code passed on every PR commit and merge during that time period.  This had been working for over a year. 

Further, we have a jupyter notebook example that calls this function [here](https://github.com/MHKiT-Software/MHKiT-Python/blob/master/examples/WPTO_hindcast_example.ipynb). You can see where this function return the values as expected.

I do not know how the NREL-REX package was doing this and I have not had a chance to look into it yet but I do know that this did work previously. Could you help support the already working functionality?

**Comment by grantbuster** [comment]
@ssolson in the future when submitting bug reports it's really really really important to explain how you expect the code in question (`rex.WaveX.get_lat_lon_df()`) to behave, not how your code behaves. I have no idea how your code works and you should not expect me to dig into your code base. 

That being said, i was able to run the code using the local dataset on Eagle (`/datasets/US_wave/v1.0.0/virtual_buoy/West_Coast/West_Coast_virtual_buoy_2010.h5`) and return valid data. I was not, however, able to reproduce the error when pointing to the HSDS wave dataset and I actually received a different error (see below). I was able to access WTK via HSDS so I think it's a wave specific error. 

Seeing as that the code works with local data, I think the error is in h5pyd. Given that I can't reproduce your error, i would suggest you investigate the actual h5pyd behavior that you expect and submit the bug report there. 

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rev/lib/python3.9/site-packages/h5pyd/_hl/dataset.py", line 1179, in __getitem__
    rsp = self.GET(req, params=params, format="binary")
  File "/opt/homebrew/Caskroom/miniforge/base/envs/rev/lib/python3.9/site-packages/h5pyd/_hl/base.py", line 979, in GET
    raise IOError("no data returned")
OSError: no data returned

**Comment by ssolson** [comment]
@grantbuster the expected behavior is in my original post. You seemed to have missed it again to I will screen shot it here for you.
![image](https://user-images.githubusercontent.com/13438942/199544559-0d2843e8-48a7-4624-a9e7-b0a448376aba.png)

I did not expect you to look into my code base, In fact if you look at my issue I used **ALL** nrel-rex recommended setting from the NREL-REX examples. 

Now why do I point to my code in my response?
I only point to my code because you seem unfamiliar with how nrel-rex works and to show you that the "spatio-temporal" problem is just in fact wrong. You seem to have now used your package to do exactly what I stated was possible in the first place. I am glad we can now agree that what I said is in fact possible.

What I am asking for support on is from following the nrel-rex documentation to use this package [here](https://nrel.github.io/rex/misc/examples.us_wave.html).  This is a supported feature of your package which is not working. Could you please help me by looking into why your package does not work as shown in your documentation?

**Comment by grantbuster** [comment]
Yep, my apologies, I did not develop the rex-wave utilities so i was unfamiliar with the custom handling of the wave spectrum dataset. My recommendation is to submit bug reports along with the expected behavior (the correct output), not just the code input snippet. Difficult for me to understand what you want the code to do if i can't see the expected output. 

I cannot reproduce your original error so I'm highly limited in what I'm able to help with. Maybe provide me with a `conda list` of your environment so that I can see what h5 versions you're using? Also what HSDS endpoint are you using? It's possible that I cannot pull the full `directional_wave_spectrum` dataset due to bandwidth issues on the NREL developer API.

**Comment by ssolson** [comment]
Okay great, and happy to do so. I am not really using just one, I have been trying a number of different combinations via github actions. I will need to follow up with a full response later.

So to check if we are on the same page, I have a commented-out line at the end of my code sample where I do receive a DataFrame back when using `energy_period`. Does this also work for you e.g. do you get a DataFrame back?

Also are you able to access the data not locally (e.g. not on the NREL network)? If not I could setup a separate repo with Github actions where we could work on this issue.

**Comment by grantbuster** [comment]
Would highly recommend debugging locally with a custom environment.

Yes I can retrieve the df for `energy_period`, I'm pretty sure the `directional_wave_spectrum` source dataset is too big for the NREL dev api so that's what's causing the new error. However, I am able to retrieve a slice of that dataset via h5pyd without any problem (see code below). I still can't reproduce your error, even with a fresh environment and the current nrel-rex and h5pyd installed from scratch. 

```
wave_file='/nrel/US_wave/virtual_buoy/West_Coast/West_Coast_virtual_buoy_2010.h5'
with WaveX(wave_file, hsds=True) as rex_waves:
    data = rex_waves['directional_wave_spectrum', 0:5, :, :, 0]
print(data.shape)

Returns:
(5, 29, 24)

**Comment by ssolson** [comment]
Thank you Grant. I do have a local environment setup I just have messed around with so many versions I will need to see exactly where I left the problem. Tomorrow I will get you a write-up of my local environment and see if I can access `directional_wave_spectrum` using the slicing method you show above. Thanks again.

**Comment by ssolson** [comment]
Hey, Grant today I set up a test repository that demonstrates the expected behavior and captures the error [here](https://github.com/ssolson/nrel-rex-issue). This could certainly be improved but wanted to show you where I was with capturing a shared environment that only uses nrel-rex and reproduces the error.

In this test I use:
  - py 3.8 
  - latest nrel-rex 
  - anaconda 

I run 2 tests using the file [test_example.py ](https://github.com/ssolson/nrel-rex-issue/blob/main/tests/test_example.py).

The test are setup and run using GitHub action which are configured in the file[main.yaml](https://github.com/ssolson/nrel-rex-issue/blob/main/.github/workflows/main.yml). What I like about this setup is the shared environment where I can demonstrate different configurations (e.g. py 3.7, 3.8, 3.9, different packages, different OS) in a repeatable and collaborative way where the issue lies. This reproduces the exact same issue I have locally.

In the the `main.yaml` file the anaconda `TEST` env is set up on [this line](https://github.com/ssolson/nrel-rex-issue/blob/main/.github/workflows/main.yml#L34). This tests are run on [this line](https://github.com/ssolson/nrel-rex-issue/blob/main/.github/workflows/main.yml#L51).

Now this test environment can be improved (and will be ) but it is sufficient I need to move on for the day.

To see the results look at the github actions page. Drop down the pytest run:
![image](https://user-images.githubusercontent.com/13438942/199807427-15d8ec9e-bac5-4d86-9671-b9a9cf66c913.png)
at the bottom, you will see that 1 passed and 1 failed (failed stack is above the message)
![image](https://user-images.githubusercontent.com/13438942/199807539-c238b572-1cbd-44df-9051-c18a4f4a4038.png)

Currently calling `energy_period` is passing but calling `directional_wave_spectrum` is failing from the test file linked above (which is just the code snippet from this initial issue). I have invited you to be a collaborator. If you create a pull request or make a merge into main a new workflow will run so that you have an environment where you can reproduce the error.

**Comment by grantbuster** [comment]
@ssolson, the `OSError: Error retrieving data: None` that you shared above is different from your original error. 

This is the same error that I'm seeing on my local machine which i think is just the limit on whatever HSDS endpoint you're hitting. If you reduce the amount of data you're pulling from the `directional_wave_spectrum` it should work fine based on what i've seen on my local.

**Comment by grantbuster** [comment]
See works fine if you retrieve a smaller slice of the spectrum data: https://github.com/ssolson/nrel-rex-issue/actions/runs/3388474195/jobs/5630498412

**Comment by ssolson** [comment]
Grant this does not "work fine" primarily because you are not using the same functionality. This call had been working for us for a long time. We need to be able to access data at a specific location, e.g. lat_lon. Less important to me but in no way is rex catching the fact that data is not being returned from the server. Rex should throw an error if data is not returned. 

How would you use tool this tool to get the lat_lon data into a dataframe?

**Comment by grantbuster** [comment]
In your original issue, the code failed on [this line](https://github.com/NREL/rex/blob/7b3926d753f9bd64893d74f08ea812bb59c2a653/rex/resource_extraction/resource_extraction.py#L1903), which does the simple data request from HSDS with h5pyd, not the dataframe conversion. The error raised was from h5pyd: `ValueError: cannot reshape array of size 0 into shape (8748,29,24)`

I added tests for this data extraction operation [here](https://github.com/ssolson/nrel-rex-issue/pull/1/files#diff-ef88d18dff1f7f3977c40a0649ba44b2c41d89676352a4d5c1fd4f3e7c81dfc7R41) and a similar extraction but with a smaller slice [here](https://github.com/ssolson/nrel-rex-issue/pull/1/files#diff-ef88d18dff1f7f3977c40a0649ba44b2c41d89676352a4d5c1fd4f3e7c81dfc7R36). The former returns a new error different from your original issue from h5pyd `OSError: Error retrieving data: None` while the latter test with the smaller slice runs fine. This leads me to believe that the new error is due to limits on the developer API endpoint that you're hitting; it is not an issue with the code or data itself. 

I still cannot reproduce your original error so I'm very limited in what I'm able to help with. 

I would recommend you get a new HSDS endpoint that has a higher bandwidth, or otherwise help me reproduce your original error reliably.

**Comment by ssolson** [comment]
Grant we are using the nrel HSDS. You can see that in my example repo. 

Is it your claim that it is impossible as things stand to request directional wave spectrum at a specific lat lon using the NREL HSDS?

**Comment by grantbuster** [comment]
Impossible is a strong word but here are some observations based on what we've tried:

1. Neither of us seem to be able to pull the full data volume from that dataset
2. The errors are being raised by h5pyd, not rex, and appear to be saying "no data has been returned"
3. Smaller datasets or a slice of the spectrum dataset are retrieved just fine
4. The original code requesting the spectrum data in dataframe works fine when pointing to the Eagle datasets

Given the above, I think the issue is in bandwidth limitations on the NREL HSDS API. It could be that your bandwidth limit was recently reduced, which would appear like something changed in the code that is just now causing failures but in reality is an external change. 

My recommendations right now are to either 1) stand up your own HSDS service so you can control your data streaming or 2) reach out to [the NREL developer network](https://developer.nrel.gov/contact/) to get your bandwidth increased.

**Comment by ssolson** [comment]
Thank you. I think with that we can close the issue for now. I appreciate your review of this issue. Wishing you the best.

**Comment by jreadey** [comment]
Hey @grantbuster - I was going to look into this myself, but it seems you have it tracked it down to an HSDS limitation of the max request size.  Actually, older versions of HSDS/h5pyd did have a limit, but it should not be the case with the current release.  You can find out more here: https://www.hdfgroup.org/2022/08/hsds-streaming/.

Can you provide a small h5pyd script that does the same HSDS request that @ssolson had fail?  I can investigate using my local HSDS as well as the NREL server.  That will be a bit easier for me compared to using rex directly.
