### ISSUE TITLE
REX or NSRDB enquiry

### ISSUE THREAD

**Issue by glarange** [NREL/rex#14]
Not sure if this is or not a feature, but am I able to extract solar irradiance for set(lat, long) 5 min. intervals?
I believe you have 2018 5 min. data available, correct?
Thanks and great repo!
Gui
PhD Student, Stony Brook U, DTS
-------------------------------------------------------------
`
from rex import NSRDBX
nsrdb_file = '/nrel/nsrdb/v3/nsrdb_2018.h5'
state='Colorado'
with NSRDBX(nsrdb_file, hsds=True) as f:
    date = '2018-07-04 18:00:00'
    dni_map = f.get_timestep_map('dni', date, region_col='state')
`
works
but not with

`
date = '2018-07-04 18:05:00'
`

`

'
**Why this feature is necessary:**
Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**A possible solution is:**

**I have considered the following alternatives:**

**Additional context**

**Charge code**
If you are at NREL, please provide a task number for the developers to implement this feature.

**Urgency / Timeframe**
When do you need this feature by? How urgent is it related to other feature requests you've made?

**Comment by glarange** [comment]
Also tried:

`f = h5pyd.File("/nrel/nsrdb/v3/nsrdb_2018.h5", 'r')
one_value = f["ghi"][42, 42]
timeseries = f["ghi"][:, 42]
len(timeseries)`

which should yield `210,240` but yields `17,520` instead. Thanks again.

**Comment by MRossol** [comment]
@glarange I'm not sure I fully understand your inquiry. Are you trying to extract a timeseries of "ghi" for a given (lat, lon) coordinate? If so you would do so as follows:
```
nsrdb_file = '/nrel/nsrdb/2018/nsrdb_conus_2018.h5'
lat_lon = (39.741931, -105.169891)
with NSRDBX(nsrdb_file, hsds=True) as f:
    lat_lon_ghi = f.get_lat_lon_df('ghi', lat_lon)
```
This will return a pandas DataFrame.
```
nsrdb_file = '/nrel/nsrdb/2018/nsrdb_conus_2018.h5'
lat_lon = (39.741931, -105.169891)
with NSRDBX(nsrdb_file, hsds=True) as f:
    lat_lon_ghi = f.get_lat_lon_ts('ghi', lat_lon)
```
While the above will return a vector of 'ghi'

**Comment by grantbuster** [comment]
Also @MRossol, it looks like he wants to extract 5min 2018 data but I dont think he's using the correct file path. Can you send him the 5min 2018 conus directory?

**Comment by grantbuster** [comment]
Oh @MRossol, nevermind, @glarange it looks like Michael included the correct conus 5min filepath in his response.
