### ISSUE TITLE
`ds_name` not defined in docs

### ISSUE THREAD

**Issue by ssolson** [NREL/rex#149]
Hey Rex team I am having issues using the API docs because I cannot find the definition of `ds_name` here: https://nrel.github.io/rex/_autosummary/rex.resource_extraction.resource_extraction.MultiYearWaveX.html#rex.resource_extraction.resource_extraction.MultiYearWaveX
![image](https://user-images.githubusercontent.com/13438942/229180313-078f6045-f09e-4bca-bb7e-15ae701aae8c.png)

Can you point me to the defintinition of `ds_name` the docs to help me use one of these methods?
E.g. I am not sure what I need to put here and `ds_name (str) – Dataset to extract` is unclear to me what I need to put here

**Comment by grantbuster** [comment]
Well so... what data are you interested in extracting? h5 files have datasets and each dataset has a name. You need to use that name to extract the data from that dataset. For example, if i was looking at NSRDB files and i wanted global horizontal irradiance (GHI), the dataset name in the h5 file is "ghi"

**Comment by ssolson** [comment]
Hey, Grant if I am making the following request:
```
from rex import MultiYearWaveX, WaveX

# data_type = '1-hour' 
data_type = '3-hour' # setting the data type to the 3-hour dataset
years = [1995]
lat_lon = (43.489171,-125.152137) 
region = wave.io.hindcast.hindcast.region_selection(lat_lon)
parameter = 'significant_wave_height'

wave_path = f'/nrel/US_wave/{region}/{region}_wave_*.h5'

wave_kwargs = {
    'tree':None,
    'unscale':True,
    'str_decode':True,
    'hsds':True,
    'years':years
}

with MultiYearWaveX(wave_path, **wave_kwargs) as rex_waves:
    gid = rex_waves.lat_lon_gid(lat_lon)
    get_gid_df(ds_name, gid)
```    
How do I know what `ds_name` is and where do I find a list of potential`ds_names`?

**Comment by grantbuster** [comment]
i think your "parameter" variable is the dataset name you're looking for. The [dsets](https://nrel.github.io/rex/_autosummary/rex.resource_extraction.resource_extraction.MultiYearWaveX.html#rex.resource_extraction.resource_extraction.MultiYearWaveX.dsets) attribute of the WaveX object will print the datasets available.
