### ISSUE TITLE
remove `google-auth-oauthlib<=0.5.3` pin

### ISSUE THREAD

**Issue by wholmgren** [NREL/rex#156]
#134 introduced a pin to `google-auth-oauthlib` due to an incompatibility with HDF5. https://github.com/HDFGroup/h5pyd/issues/126 suggests that the problem is resolved. Can `rex` remove the pin?

Context is that a colleague needs `NREL/PVDegradationTools`, which depends on `rex`, in an environment with an incompatible minimum pin.

**Comment by ppinchuk** [comment]
rex version 0.2.83 is [now up on PyPi](https://pypi.org/project/NREL-rex/0.2.83/) are removes the pinned req. Hope this helps! Please reach out if you have any other issues :)

**Comment by wholmgren** [comment]
I never imagined a release within hours of reporting this - thanks a bunch!
