### ISSUE TITLE
Unable to access 2021 NSRDB data

### ISSUE THREAD

**Issue by annacheyette** [NREL/rex#164]
I am unable to access 2021 NSRDB data using `NSRDBX`: 

```python
from rex import NSRDBX

nsrdb_file = f'/nrel/nsrdb/v3/nsrdb_2021.h5'
nrel = (39.741931, -105.169891)

with NSRDBX(nsrdb_file, hsds=True) as f:
    nrel_dni = f.get_SAM_lat_lon((nrel))
```
results in `OSError: [Errno 503] Service Unavailable`. Previous years work successfully. It appears that 2021 data should be published already (e.g. [https://nsrdb.nrel.gov/data-sets/us-data](https://nsrdb.nrel.gov/data-sets/us-data)). Is there a delay getting this data access via rex? If so, is there a timeline for when new data will be available via rex?

Thank you for your help.

**Comment by annacheyette** [comment]
I've been able to follow these instructions and get HSDS downloaded locally on my laptop. I am successfully able to download data for years prior to 2021 (e.g., i can run 
```python
nsrdb_file = f'/nrel/nsrdb/v3/nsrdb_2020.h5'
nrel = (39.741931, -105.169891)

with NSRDBX(nsrdb_file, hsds=True) as f:
    nrel_dni = f.get_SAM_lat_lon((nrel))
``` 
successfully). I am just unable to get the 2021 data to work. Do you know if the server will update with 2021 data? Thanks!

**Comment by grantbuster** [comment]
Try using the path `/nrel/nsrdb/current/nsrdb_2021.h5`. The /v3/ folder is deprecated. I'll ask to have it removed.

**Comment by annacheyette** [comment]
Thanks so much, that new path works! I'm also able to download the 2022 data at this path, which is great. Do you know generally how long it takes to get data added? e.g., how long after 2023 ends will it take for 2023 data to get uploaded?

**Comment by grantbuster** [comment]
It typically takes a few months, at the latest we release the data in the following september. This is driven mostly by the DOE fiscal year.
