### ISSUE TITLE
Enable MultiFileResource to handle list of file paths

### ISSUE THREAD

**Issue by grantbuster** [NREL/rex#34]
**Why this feature is necessary:**
reV supply curve aggregation might pull gen and econ outputs from different projects. If we had a MultFileResource handler that could take a list of file paths, we could point to both source files easily. Combining might be onorous because of the generation CF profiles. Also, if econ is a batch-permutation run, the number of unique permutations would become prohibitive. 

**A possible solution is:**
Maybe implement somewhere close to here? We would need to check that time index and meta are the same / similar.

https://github.com/NREL/rex/blob/a5ba01ffdc4fa4c021a3db10a714334f8c4ebf46/rex/resource.py#L1246

**Charge code**
WEPG 10348 08.01.06

**Urgency / Timeframe**
ASAP - end of FY bat curtailment runs are high priority for Galen.

**Comment by grantbuster** [comment]
example:

```
with MultFileResource([rev_gen.h5, rev_econ.h5]) as res:
```

where gen and econ have the same meta data but different datasets. One or both of the files may not have a time_index dataset.

**Comment by MRossol** [comment]
implemented in #35
