### ISSUE TITLE
wave date download broken?

### ISSUE THREAD

**Issue by ryancoe** [NREL/rex#67]
**Bug Description**
I am able to use `rex` to download wind and NSRDB data, but I get an error for the wave data. I am however able to access the wave data directly on AWS ... maybe I'm missing something, but I think there may be a bug

**Full Traceback**
using the example here: https://github.com/NREL/rex/tree/master/examples/US_Wave
```
 from rex import WaveX
   ...: 
   ...: wave_file = '/datasets/US_wave/v1.0.0/US_wave_2010.h5'
   ...: with WaveX(wave_file) as f:
   ...:     meta = f.meta
   ...:     time_index = f.time_index
   ...:     swh = f['significant_wave_height']
   ...: 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-ed94d7033cc4> in <module>
      2 
      3 wave_file = '/datasets/US_wave/v1.0.0/US_wave_2010.h5'
----> 4 with WaveX(wave_file) as f:
      5     meta = f.meta
      6     time_index = f.time_index

~/anaconda3/envs/waveResource/lib/python3.8/site-packages/rex/resource_extraction/resource_extraction.py in __init__(self, wave_h5, tree, unscale, hsds, str_decode, group)
   1405             Group within .h5 resource file to open
   1406         """
-> 1407         super().__init__(wave_h5, unscale=unscale, str_decode=str_decode,
   1408                          group=group, hsds=hsds, tree=tree,
   1409                          res_cls=WaveResource)

~/anaconda3/envs/waveResource/lib/python3.8/site-packages/rex/resource_extraction/resource_extraction.py in __init__(self, res_h5, res_cls, tree, unscale, hsds, str_decode, group)
     53             Group within .h5 resource file to open
     54         """
---> 55         self._res = res_cls(res_h5, unscale=unscale, hsds=hsds,
     56                             str_decode=str_decode, group=group)
     57         self._tree = tree

~/anaconda3/envs/waveResource/lib/python3.8/site-packages/rex/resource.py in __init__(self, h5_file, unscale, hsds, str_decode, group)
    723             self._h5 = h5pyd.File(self.h5_file, 'r')
    724         else:
--> 725             self._h5 = h5py.File(self.h5_file, 'r')
    726 
    727         self._group = group

~/anaconda3/envs/waveResource/lib/python3.8/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, **kwds)
    422             with phil:
    423                 fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0, **kwds)
--> 424                 fid = make_fid(name, mode, userblock_size,
    425                                fapl, fcpl=make_fcpl(track_order=track_order, fs_strategy=fs_strategy,
    426                                fs_persist=fs_persist, fs_threshold=fs_threshold),

~/anaconda3/envs/waveResource/lib/python3.8/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    188         if swmr and swmr_support:
    189             flags |= h5f.ACC_SWMR_READ
--> 190         fid = h5f.open(name, flags, fapl=fapl)
    191     elif mode == 'r+':
    192         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = '/datasets/US_wave/v1.0.0/US_wave_2010.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
```

**System (please complete the following information):**
 - OS: macOS 10.14.6
 - Compute hardware: macbook pro
 - Version 0.2.34

**Comment by grantbuster** [comment]
Try changing the filepath to one that exists. As the error says: `"No such file or directory"`

**Comment by ryancoe** [comment]
Thanks @grantbuster - Yes, I agree the `h5` file path is probably wrong, can you give me a correct one (this is the path listed in your examples)? Neither of the follow work

- [rex/examples/US_Wave/README.rst](https://github.com/NREL/rex/tree/master/examples/US_Wave): `/nrel/us-wave/US_wave_2010.h5`
- [rex/examples/US_Wave/US_Wave.md](https://github.com/NREL/rex/blob/master/examples/US_Wave/US_Wave.md): `/datasets/US_wave/v1.0.0/US_wave_2010.h5`

**Comment by grantbuster** [comment]
Are you on Eagle? if so, this is a valid filepath. I'm not sure about the file structure on AWS but I've included the OEDI registry. If you cant find what you're looking for maybe Michael can help and update the README's. Regardless, this is not a software bug. 

/lustre/eaglefs/datasets/US_wave/v1.0.0/West_Coast/West_Coast_wave_2010.h5
https://registry.opendata.aws/wpto-pds-us-wave/

**Comment by ryancoe** [comment]
@grantbuster - No, I'm not on Eagle. Per my comment [above](https://github.com/NREL/rex/issues/67#issue-780985104), I can access the data via AWS, but I also don't know how the AWS path relates to the HSDS path.

**Comment by MRossol** [comment]
@ryancoe , why are you trying to use HSDS and AWS when you are at NREL and thus have access to Eagle? As noted in our [HSDS-example](https://github.com/nrel/hsds-examples):

NREL's HSDS service provides public access to several of DOEs high-value datasets available internally on the Eagle HCP System. Due to the high demand for the HSDS service, users with access to NREL’s HPC should pursue direct access through that system.

Our HSDS service is not meant to support internal NREL research, more importantly, you will get MUCH better performance on the HPC.

**Comment by ryancoe** [comment]
I'm at Sandia, not NREL ;)

**Comment by MRossol** [comment]
Please checkout the hsds-examples repo on how to get HSDS installed. to search the valid "domains" you can use:
``hsls /nrel/``

**Comment by MRossol** [comment]
Example links have been updated
