### ISSUE TITLE
Logger path manipulation

### ISSUE THREAD

**Issue by grantbuster** [NREL/rex#90]
@MRossol should this line use `os.path.realpath()` instead of `normpath`? If the handler is `./log_file.log` normpath breaks on linux. You already use realpath on line 73 of the same file. 

https://github.com/NREL/rex/blob/e747f937250f3f3383bcf52d7955ca87c194fb12/rex/utilities/loggers.py#L279

**Comment by MRossol** [comment]
probably, stupid normpath!

**Comment by MRossol** [comment]
@grantbuster  do you need this released?

**Comment by grantbuster** [comment]
No this is just for a notebook im working on. Easy enough to specify the full filepath but it looked like something we'd want to patch.

**Comment by MRossol** [comment]
Already patched on main!
