### ISSUE TITLE
Can't get SAM dataset with wind direction data

### ISSUE THREAD

**Issue by mike-welch** [NREL/rex#98]
When calling `get_sam_lat_long()` for a wind resource with `require_wind_dir=True` I am encountering an KeyError on the following codeblock:

https://github.com/NREL/rex/blob/5c4a70685e87ceb5190fabf5bebb2d6665f68607/rex/renewable_resource.py#L967-L969

Here's an excerpt from the stack trace:

```
KeyError: 'winddirection'
  File ".\venv\Lib\site-packages\rex\renewable_resource.py", line 969, in get_SAM_df
    SAMResource.WIND_DATA_RANGES[var], [site])
  File ".\venv\Lib\site-packages\rex\resource_extraction\resource_extraction.py", line 1438, in get_SAM_gid
    df = self.resource.get_SAM_df(res_id, hub_height, **kwargs)
  File ".\venv\Lib\site-packages\rex\resource_extraction\resource_extraction.py", line 1482, in get_SAM_lat_lon
    SAM_df = self.get_SAM_gid(hub_height, gid, out_path=out_path, **kwargs)
  ...
```

After reviewing the behavior, the root cause is the `winddirection` key not being set here:
https://github.com/NREL/rex/blob/5c4a70685e87ceb5190fabf5bebb2d6665f68607/rex/sam_resource.py#L71-L74

I inserted `winddirection: (0, 360)` and the code runs as expected.

**Comment by grantbuster** [comment]
Agreed, implemented your fix in 72cf56dfa0438a9090986577d1c1d2e495369441. Thanks for the bug and the fix!
